import Head from 'next/head';
import React, {Suspense} from 'react'
import { Container, Box, Stack } from '@mui/material';
import '../components/translate/i18next'
import MoviesList from '@/components/moviesList';
import Subscribe from '@/components/header/Subscribe'
import useRequest from '@/hooks/useRequest';
import Hero from '@/components/hero';
import { Movies } from '@/components/interfaces/movie';
import MyTitle from '@/components/content/myTitle';
import MyText from '@/components/content/myText';

export default function Home() {

  const url = 'http://localhost:3003/info?genres=4&limit=15';
  const urlCom = 'http://localhost:3003/info?genres=8&limit=15';

  const movies:Movies = useRequest(url);
  const moviesCom:Movies = useRequest(urlCom);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />    
      </Head>
      <Suspense fallback={<div>Loading...</div>}>
      <main>
        <Hero />
        <Container maxWidth={false} sx={{ width: '77.5rem', mb:'1rem' }}>
          <Subscribe />
          <MyTitle text='Онлайн-кинотеатр Иви: фильмы в хорошем качестве всегда приносят настоящее удовольствие'/>
          <Stack direction='column' gap={1}>
          

          </Stack>
     

          <MoviesList movies = {movies} title={'Драмы'} />
          <MoviesList movies = {moviesCom} title={'Комедии'} />

        </Container>

              
      </main>
      </Suspense>
    </>
  )
}
