import Head from 'next/head';
import React, {Suspense} from 'react'
import { Container } from '@mui/material';
import '../components/translate/i18next'
import FilmList from '@/components/moviesListList';
import Subscribe from '@/components/header/Subscribe'
import useRequest from '@/hooks/useRequest';
import Hero from '@/components/hero';

export default function Home() {

  const url = 'http://localhost:3003/info';
  const films:any = useRequest(url);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />    
      </Head>
      <Suspense fallback={<div>Loading...</div>}>
      <main>
        <Hero />
        <Container maxWidth={false} sx={{ width: '1240px', mb:'1rem' }}>
          <Subscribe /> 
          <FilmList films = {films}/>
        </Container>

              
      </main>
      </Suspense>
    </>
  )
}
